[server]
headless = true
port = 8501
baseUrlPath = ""
logLevel = "info"
enableCORS = false
maxUploadSize = 200
enableXsrfProtection = false

[browser]
serverAddress = "localhost"
serverHeadless = true

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
